### ISSUE TITLE
Floor Tile Duplication In Dimensional Rectifier

### ISSUE THREAD

**Issue by Ninja-Hinja42** [TheJSHuA/JavaDungeons#10]
In the Dimensional Rectifier, 1 Floor Tile can become 1 Dirty Floor Tile
![2020-04-30_12 30 55](https://user-images.githubusercontent.com/36712216/80735305-7f387280-8ade-11ea-968c-21bb23b564f2.png)
But 1 Dirty Floor Tile becomes 2 Floor Tiles
![2020-04-30_12 31 04](https://user-images.githubusercontent.com/36712216/80735362-937c6f80-8ade-11ea-9235-04773224aa6e.png)

**Comment by ashie404** [comment]
The Dimensional Rectifier and it's recipes are being removed for a better approach to crafting in newer versions.
