### ISSUE TITLE
JavaDungeons crashes during launch

### ISSUE THREAD

**Issue by Quizer9O8** [TheJSHuA/JavaDungeons#11]
**Crash Log**
https://pastebin.com/idLTKnbV

**Additional Content**
![afbeelding](https://user-images.githubusercontent.com/19509275/82821602-b06d4e00-9ea4-11ea-8d33-ccd17787e551.png)
![afbeelding](https://user-images.githubusercontent.com/19509275/82821842-0fcb5e00-9ea5-11ea-9e89-131faf1f29b1.png)

**Comment by ashie404** [comment]
your version of Fabric API seems to be outdated, you need at least Fabric API 0.10.0

**Comment by Quizer9O8** [comment]
Reinstalling the entire custom modpack seems to have solved the problem.
