### ISSUE TITLE
Lakes in Cacti Canyon

### ISSUE THREAD

**Issue by IAmSneak** [TheJSHuA/JavaDungeons#14]
![2020-06-08_00 16 59](https://user-images.githubusercontent.com/66091019/83992367-1a163f00-a91e-11ea-86d1-68cc798ef0ef.png)

The cacti canyon has lakes in it that have land generate over it.

**Comment by ashie404** [comment]
I'll look into it. Just from a few quick tests, it appears this also occurs in the vanilla world generator code this is based on, so it might be a bit harder to fix.

**Comment by ashie404** [comment]
this has not been fixed, but closing since I can not find a solution as of right now.
