### ISSUE TITLE
Water Plant don't match with Dungeon Water

### ISSUE THREAD

**Issue by xrmnpr** [TheJSHuA/JavaDungeons#25]
Hey !
When I place a "Water Plant" in the "Dungeon water", that Dungeon water is instantly replaced by the default water of the minecraft Vanilla.
Something else, "Bridge planks" make the same issue.
These blocks don't seem to work with WaterLogging.
Thank you in advance.
Asimoov123

**Comment by ashie404** [comment]
In order for waterlogging with custom fluids to work, you should install the mod Towelette: https://www.curseforge.com/minecraft/mc-mods/towelette
